# Generated by Django 5.0.1 on 2024-02-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_comment_article_comment_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='website',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default=1, upload_to='media/articles'),
            preserve_default=False,
        ),
    ]
