# Generated by Django 5.0.1 on 2024-02-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_aboutme_options_alter_achievements_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
