# Generated by Django 5.0.1 on 2024-02-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skills_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='is_top_3',
            field=models.BooleanField(default=False),
        ),
    ]
