# Generated by Django 5.0.1 on 2024-02-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skills_is_top_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='cvv',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
